steps:
  - name: 'gcr.io/cloud-builders/java/javac:8'
    entrypoint: 'bash'
    args: ['./gradlew', 'build']
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/spring-boot-hello-world', '.' ]
images:
  - 'gcr.io/$PROJECT_ID/spring-boot-hello-world'