steps:
  - id: 'decrypt-file'
    name: 'gcr.io/cloud-builders/gcloud'
    args:
      - kms
      - decrypt
      - --ciphertext-file=id_rsa_2.enc
      - --plaintext-file=/root/.ssh/id_rsa
      - --location=global
      - --keyring=my-keyring
      - --key=github-key
    volumes:
      - name: 'ssh'
        path: /root/.ssh
#  - id: 'build jar artifact'
#    name: 'gcr.io/cloud-builders/java/javac:8'
#    entrypoint: 'bash'
#    args: ['./gradlew', 'build']
#  - id: 'build docker image'
#    name: 'gcr.io/cloud-builders/docker'
#    args: ['build', '-t', 'gcr.io/$PROJECT_ID/spring-boot-hello-world:$SHORT_SHA.$BUILD_ID', '.']
#  - id: 'push docker image to registry'
#    name: 'gcr.io/cloud-builders/docker'
#    args: ['push', 'gcr.io/$PROJECT_ID/spring-boot-hello-world:$SHORT_SHA.$BUILD_ID']
  - id: 'tag version'
    name: 'gcr.io/cloud-builders/git'
    args: ['tag', 'image-$SHORT_SHA.$BUILD_ID']
  - id: 'push new tags'
    name: 'gcr.io/cloud-builders/git'
    args: ['push', '--tags']