steps:
  - id: 'build jar artifact'
    name: 'gcr.io/cloud-builders/java/javac:8'
    entrypoint: 'bash'
    args: ['./gradlew', 'build']
  - id: 'build docker image'
    name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/spring-boot-hello-world:$SHORT_SHA.$BUILD_ID',
      '-t', 'gcr.io/$PROJECT_ID/spring-boot-hello-world:latest',
      '.'
    ]
images:
  - 'gcr.io/$PROJECT_ID/spring-boot-hello-world'